### ISSUE TITLE
Minor functionality broken with JQuery UI 1.12.1

### ISSUE THREAD

**Issue by Agentis** [evoluteur/structured-filter#15]
Noticed the following behavior when JQuery UI 1.12.1 was used alongside this plugin:

- Close button/icon inside a filtering box (which is intended to remove the filter object from the list) does not remove the item, and instead opens it for editing

- Text description of filtering behaves oddly when being edited after initial creation. Would end up with odd strings like "Room does not contain 'a' does not contain 'b' does not contain 'c'"

Excellent plugin btw.

**Comment by evoluteur** [comment]
Done.
