### ISSUE TITLE
Collision with Bootstrap Javascript

### ISSUE THREAD

**Issue by samcov** [evoluteur/structured-filter#16]
The css for structured-filter does not work if used with bootstrap.

The offender is not in the css, but in the javascript. To reproduce the problem, simply add the following,

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

Then lower the jquery version to something under version 3, which bootstrap doesn't like. Then the styling will go away.

It only occurs when the .js is there, removing the bootstrap css and leaving the js causes the problem.

**Comment by evoluteur** [comment]
UI libraries do not always play well together. If you want Bootstrap, I would recommand using the structured-filter which is part of Evolutility-UI-jQuery. It was re-written for Bootstrap and doesn't use jQuery-UI.
http://evoluteur.github.io/evolutility-ui-jquery/

**Comment by samcov** [comment]
Ok, Thanks.
