### ISSUE TITLE
conflict between structured filter styles and Bootstrap buttons

### ISSUE THREAD

**Issue by AbhishekPatil9844** [evoluteur/structured-filter#18]

**Comment by evoluteur** [comment]
I do not recommend using both jQuery-UI style and Bootstrap at the same time.
I have another version of the structured-filer (which uses Bootstrap) as part of Evolutility-UI-jQuery.
https://github.com/evoluteur/evolutility-ui-jquery

**Comment by AbhishekPatil9844** [comment]
Okay Thanks, I will try with another version.

**Comment by AbhishekPatil9844** [comment]
Can I use evolutility-ui-jquery for server side pagination for the
collection like backgrid?

**Comment by evoluteur** [comment]
Sorry, it is not implemented. It is not difficult to do. I have it on Evolutility-UI-React.

**Comment by AbhishekPatil9844** [comment]
Okay, Thanks for update Olivier. Currently, am using backbone, backgrid and
Structured filter. Which was working fine until I started to use "Bootstrap
Button.js". And Your evolutility-ui-jquerry is Awesome. It is exactly what
I need. The only problem is now is, I need pagination support like backgrid
also. Anyway, your work is awesome,  evolutility-ui-jquerry is awesome.

**Comment by AbhishekPatil9844** [comment]
Hi Olivier

Hope you are doing good, I need your help, Can I add relative date type
option in date option. I have attached sample image below. Please find the
attached file and let me know.
