### ISSUE TITLE
Filrer as OData query

### ISSUE THREAD

**Issue by Misiu** [evoluteur/structured-filter#19]
Hi there, first of all thank You for such great project. I'm wondering if it is possible to create OData query from filter build with Your builder.
I'd like to use Your builder to create filter that could be send to OData endpoint.

**Comment by evoluteur** [comment]
That is a very good idea and it should be possible. 
The API of Structured-Filter only covers a subset of the OData API and uses different conventions but the structure of both are similar enough to make it possible. I think the easiest would be to make a wrapper around Structured-Filter.
