### ISSUE TITLE
Having trouble getting the x close synble to show  up on the filters

### ISSUE THREAD

**Issue by zach2825** [evoluteur/structured-filter#2]
After i create a filter. The little x to remove the filter will not show up. Could you point me in the direction to resolve this?

Im including jquery base css and light theme css and jquery jquery ui and the project js
![missingfilterclosebutton](https://cloud.githubusercontent.com/assets/4049321/7522935/3c1bc208-f4ad-11e4-8698-2a3937d02620.png)

Thank you for your time in advanced.

**Comment by zach2825** [comment]
I wanted to add that its not adding the element with the class "ui-button-icon-secondary ui-icon ui-icon-close" to the new filter.

Your example
![yourclosefilter](https://cloud.githubusercontent.com/assets/4049321/7523358/153ac8a2-f4b0-11e4-8b61-da0536849c77.png)


My code
![myfilter](https://cloud.githubusercontent.com/assets/4049321/7523356/110ba030-f4b0-11e4-8728-b7dee4f5fa1b.png)

p.s. this project is amazing im happy i found it.

**Comment by evoluteur** [comment]
It seems like you modified the classes. For the button to show up you need the jQuery UI class or you need to create a class that would give provide the same look.
