### ISSUE TITLE
can't get the remove icon to show

### ISSUE THREAD

**Issue by mhmd1983** [evoluteur/structured-filter#22]
hello,
thanks for the nice code, but I'm having a problem showing the x icon to remove the a single filter 
i'm using bootstrap 3.3.7 and a custom jquery-ui theme for bootstrap

**Comment by evoluteur** [comment]
The html is <span class="ui-button-icon ui-icon ui-icon-close"></span>
If you copy and paste the above html, you should see a close icon (x). Otherwise, you must be missing some css files.
