### ISSUE TITLE
Run time add new fields in structFilter

### ISSUE THREAD

**Issue by Ponvijaykumar** [evoluteur/structured-filter#27]
It's possible to add new **fields** object { id: "FieldID", type: "text", label: "FieldLabel" } in existing
**structFilter**.

$("#myFilter").structFilter({
    fields: [
        {type:"text", id:"lastname", label:"Lastname"},
        {type:"text", id:"firstname", label:"Firstname"},
    ]
});

**Comment by Ponvijaykumar** [comment]
I try to destroy and re-create **structFilter** 

But not able to destroy the existing **structFilter**.

![image](https://user-images.githubusercontent.com/33975575/63636296-077e9200-c68b-11e9-9294-4f02cbf24021.png)

**Comment by evoluteur** [comment]
Thanks for letting me know. I just fixed the destroy method.
